# Creating arrays with NumPy

In [1]:
import numpy as np

### Converting from a list

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1, my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_lists)

In [11]:
# Matrix
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int64')

### Array of all zeros (float)

In [24]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
my_zeros_array = np.zeros(5)

In [18]:
my_zeros_array.dtype

dtype('float64')

In [26]:
# Or :
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

### Array of ones

In [25]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### Identity Matrix

In [27]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### Range for arrays

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])