In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Square root
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
# Exponential
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
# Random array (normal distribution)
A = np.random.randn(10)
A

array([-0.27201816, -0.48079924, -0.67836082, -0.40572061, -0.6210894 ,
       -0.35702571,  2.12094281,  0.12323561,  0.90062009,  0.52313025])

In [7]:
B = np.random.randn(10)
B

array([ 0.49049302, -1.97953899, -0.52848479,  1.10203444, -0.5840113 ,
        0.41214777,  0.0759625 ,  0.24894797, -0.71538109, -1.51816019])

### Binary functions

In [8]:
# Adding arrays
np.add(A, B)

array([ 0.21847486, -2.46033824, -1.20684562,  0.69631382, -1.2051007 ,
        0.05512206,  2.19690532,  0.37218358,  0.185239  , -0.99502994])

In [9]:
# Max of arrays
# Maximum for each value of A and B
np.maximum(A, B)

array([ 0.49049302, -0.48079924, -0.52848479,  1.10203444, -0.5840113 ,
        0.41214777,  2.12094281,  0.24894797,  0.90062009,  0.52313025])

### List of functions

In [10]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True